/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sg.app.gradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public boolean anotherLibraryMethod() {
        return false;
    }
}
